<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="93617" started-at="2019-03-17T05:18:17Z" finished-at="2019-03-17T05:19:50Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="93617" started-at="2019-03-17T05:18:17Z" finished-at="2019-03-17T05:19:50Z">
      <class name="tests.LoginTests">
        <test-method status="PASS" signature="setupEnvironment()[pri:0, instance:tests.LoginTests@64c64813]" name="setupEnvironment" is-config="true" duration-ms="74056" started-at="2019-03-17T10:48:17Z" finished-at="2019-03-17T10:49:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupEnvironment -->
        <test-method status="FAIL" signature="verifyLogin()[pri:0, instance:tests.LoginTests@64c64813]" name="verifyLogin" duration-ms="19474" started-at="2019-03-17T10:49:31Z" description="login test" finished-at="2019-03-17T10:49:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[message expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: message expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at tests.LoginTests.verifyLogin(LoginTests.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method status="PASS" signature="closeEnvironment()[pri:0, instance:tests.LoginTests@64c64813]" name="closeEnvironment" is-config="true" duration-ms="72" started-at="2019-03-17T10:49:50Z" finished-at="2019-03-17T10:49:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeEnvironment -->
      </class> <!-- tests.LoginTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
